from sqlalchemy import String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin


class User(Base, UUIDPrimaryKeyMixin, TimestampMixin, SoftDeleteMixin):
    """
    Users table - The highest-level logical boundary for tenant isolation.
    Ref: Database Design §2.1
    """
    __tablename__ = "users"

    tenant_id: Mapped[str] = mapped_column(String(50), nullable=False)
    phone_number: Mapped[str] = mapped_column(String(20), nullable=False)
    email: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Note: Unique constraints and indexes will be generated by Alembic or defined here later.
    
    # Relationships
    contacts: Mapped[list["Contact"]] = relationship("Contact", back_populates="user")
    conversations: Mapped[list["Conversation"]] = relationship("Conversation", back_populates="user")
    agent_states: Mapped[list["AgentState"]] = relationship("AgentState", back_populates="user")
